"""
K-Bio Pipeline Tracker - 기업 설정 파일
DART corp_code: https://opendart.fss.or.kr/api/corpCode.xml?crtfc_key=API_KEY 에서 조회
"""

COMPANIES = {
    "abl": {
        "name": "에이비엘바이오",
        "ticker": "298380",
        "market": "KOSDAQ",
        "dart_corp_code": "01011339",
        "ct_search_terms": ["ABL Bio", "ABL301", "ABL503", "ABL111", "Grabody", "givastomig"],
        "news_keywords": ["에이비엘바이오", "ABL바이오", "ABL Bio", "ABL301", "ABL111"],
    },
    "alteogen": {
        "name": "알테오젠",
        "ticker": "196170",
        "market": "KOSDAQ",
        "dart_corp_code": "00862491",
        "ct_search_terms": ["Alteogen", "ALT-B4", "berahyaluronidase alfa", "KEYTRUDA subcutaneous"],
        "news_keywords": ["알테오젠", "Alteogen", "키트루다SC", "피하주사"],
    },
    "legochem": {
        "name": "리가켐바이오",
        "ticker": "141080",
        "market": "KOSDAQ",
        "dart_corp_code": "00878422",
        "ct_search_terms": ["LegoChem", "LCB14", "LCB84", "LCB71", "ConjuALL"],
        "news_keywords": ["리가켐바이오", "LegoChem", "ADC", "LCB14"],
    },
    "voronoi": {
        "name": "보로노이",
        "ticker": "310210",
        "market": "KOSDAQ",
        "dart_corp_code": "01317283",
        "ct_search_terms": ["Voronoi", "VRN11", "VRN10", "EGFR C797S"],
        "news_keywords": ["보로노이", "Voronoi", "VRN11", "4세대 EGFR"],
    },
    "peptron": {
        "name": "펩트론",
        "ticker": "087010",
        "market": "KOSDAQ",
        "dart_corp_code": "00372628",
        "ct_search_terms": ["Peptron", "PT320", "exenatide"],
        "news_keywords": ["펩트론", "Peptron", "PT320"],
    },
    "ildong": {
        "name": "일동제약",
        "ticker": "249420",
        "market": "KOSDAQ",
        "dart_corp_code": "00109655",
        "ct_search_terms": ["Ildong", "IDX-1197", "HK-660S"],
        "news_keywords": ["일동제약", "Ildong"],
    },
    "hanlim": {
        "name": "한림제약",
        "ticker": "002390",
        "market": "KOSPI",
        "dart_corp_code": "00026380",
        "ct_search_terms": ["Hanlim", "HL161", "batoclimab", "FcRn"],
        "news_keywords": ["한림제약", "HL161", "바토클리맙", "FcRn"],
    },
    "inventisbio": {
        "name": "인벤티스바이오",
        "ticker": "394280",
        "market": "KOSDAQ",
        "dart_corp_code": "",
        "ct_search_terms": ["Inventisbio", "OLX101A"],
        "news_keywords": ["인벤티스바이오", "OLX101A"],
    },
    "hlb": {
        "name": "HLB",
        "ticker": "028300",
        "market": "KOSDAQ",
        "dart_corp_code": "00126380",
        "ct_search_terms": ["rivoceranib", "apatinib", "HLB", "Elevar", "camrelizumab HCC"],
        "news_keywords": ["HLB", "리보세라닙", "아파티닙", "rivoceranib", "Elevar"],
    },
    "yuhan": {
        "name": "유한양행",
        "ticker": "000100",
        "market": "KOSPI",
        "dart_corp_code": "00088947",
        "ct_search_terms": ["lazertinib", "Rybrevant", "MARIPOSA", "Yuhan", "amivantamab lazertinib"],
        "news_keywords": ["유한양행", "렉라자", "lazertinib", "Rybrevant"],
    },
    "skbp": {
        "name": "SK바이오팜",
        "ticker": "326030",
        "market": "KOSPI",
        "dart_corp_code": "00941058",
        "ct_search_terms": ["cenobamate", "Xcopri", "SKL-10345", "SK Biopharmaceuticals"],
        "news_keywords": ["SK바이오팜", "세노바메이트", "엑스코프리", "cenobamate"],
    },
    "celltrion": {
        "name": "셀트리온",
        "ticker": "068270",
        "market": "KOSPI",
        "dart_corp_code": "00254045",
        "ct_search_terms": ["Celltrion", "CT-P13", "CT-P6", "CT-P17", "CT-P16", "infliximab biosimilar"],
        "news_keywords": ["셀트리온", "Celltrion", "바이오시밀러", "CT-P13"],
    },
    "gi-innovation": {
        "name": "지아이이노베이션",
        "ticker": "065150",
        "market": "KOSDAQ",
        "dart_corp_code": "00430798",
        "ct_search_terms": ["GI Innovation", "GI-101", "CD80 IL-2", "immunocytokine"],
        "news_keywords": ["지아이이노베이션", "GI-101", "GI Innovation"],
    },
    "oscotec": {
        "name": "오스코텍",
        "ticker": "039200",
        "market": "KOSDAQ",
        "dart_corp_code": "00298784",
        "ct_search_terms": ["Oscotec", "ADEL-Y01", "anti-tau", "Adel"],
        "news_keywords": ["오스코텍", "아델", "ADEL-Y01", "타우항체"],
    },
    "medpacto": {
        "name": "메드팩토",
        "ticker": "235980",
        "market": "KOSDAQ",
        "dart_corp_code": "01091882",
        "ct_search_terms": ["Medpacto", "vactosertib", "TEW-7197", "TGF-beta inhibitor"],
        "news_keywords": ["메드팩토", "백토서팁", "vactosertib", "TGF-β"],
    },
    "abclon": {
        "name": "앱클론",
        "ticker": "174900",
        "market": "KOSDAQ",
        "dart_corp_code": "01105546",
        "ct_search_terms": ["AbClon", "AC101", "AT101", "HER2 ADC CAR-T"],
        "news_keywords": ["앱클론", "AbClon", "AC101", "CAR-T"],
    },
    "pharmaresearch": {
        "name": "파마리서치",
        "ticker": "214450",
        "market": "KOSDAQ",
        "dart_corp_code": "01133378",
        "ct_search_terms": ["PharmaResearch", "PDRN", "Rejuran", "polynucleotide"],
        "news_keywords": ["파마리서치", "리쥬란", "Rejuran", "PDRN"],
    },
    "genome": {
        "name": "지놈앤컴퍼니",
        "ticker": "314130",
        "market": "KOSDAQ",
        "dart_corp_code": "01368447",
        "ct_search_terms": ["Genome and Company", "GEN-001", "microbiome cancer"],
        "news_keywords": ["지놈앤컴퍼니", "GEN-001", "마이크로바이옴"],
    },
    "prestige": {
        "name": "프레스티지바이오파마",
        "ticker": "950210",
        "market": "KOSDAQ",
        "dart_corp_code": "01358527",
        "ct_search_terms": ["Prestige BioPharma", "HD204", "HD201", "bevacizumab biosimilar"],
        "news_keywords": ["프레스티지바이오파마", "Prestige BioPharma", "바이오시밀러"],
    },
    "metsera": {
        "name": "멧세라",
        "ticker": "-",
        "market": "비상장",
        "dart_corp_code": "",
        "ct_search_terms": ["Metsera", "MET-0976", "oral GLP-1"],
        "news_keywords": ["멧세라", "Metsera", "MET-0976", "경구 GLP-1"],
    },
}
